vim.o.hidden=true                              --Required to keep multiple buffers open multiple buffers
vim.o.fileencoding="utf-8"                  --The encoding written to file
vim.cmd('set shortmess+=c')
vim.o.pumheight=10                        --Makes popup menu smaller
vim.o.cmdheight=2                         --More space for displaying messages
vim.o.completeopt="menuone,noinsert,noselect"
vim.o.mouse="a"                             --Enable your mouse
vim.wo.wrap=false                              --Display long lines as just one line
vim.cmd('set whichwrap+=<,>,[,],h,l')
vim.o.ignorecase=true
vim.o.smartcase=true
vim.o.splitright=true                          --Vertical splits will automatically be to the right
vim.o.splitbelow=true                          --Horizontal splits will automatically be below
vim.bo.expandtab=true                           --Converts tabs to spaces
vim.bo.smartindent=true                         --Makes indenting smart
vim.cmd('set ts=2')                           --Insert 2 spaces for a tab
vim.cmd('set sw=2')                        --Change the number of space characters inserted for indentation
vim.o.showtabline=2                       --Always show tabs
vim.wo.number = true
vim.wo.relativenumber = true
vim.o.signcolumn="yes"                      --Always show the signcolumn, otherwise it would shift the text each time
vim.wo.cursorline=true                          --Enable highlighting of the current line
vim.o.ruler=true
vim.o.showmode=false                          --We don't need to see things like -- INSERT -- anymore
vim.o.scrolloff=5
vim.o.backup=false                            -- Better intergration with lsp servers
vim.o.writebackup=false                       -- Better intergration with lsp servers
vim.o.swapfile=false
vim.o.updatetime=300                      --Faster completion
vim.o.timeoutlen=100                      --By default timeoutlen is 1000 ms
vim.o.clipboard="unnamedplus"               --Copy paste between vim and everything else
vim.o.conceallevel=0                      --So that I can see `` in markdown files
vim.cmd('set iskeyword+=-')                  --treat dash separated words as a word text object"
vim.o.termguicolors=true
vim.o.guifont = "Hack:h18"
